IF DB_ID (N'moneydb') IS NULL
create database moneydb
GO

USE moneydb;

IF OBJECT_ID('dbo.T_CURRENCY', 'U') IS NOT NULL DROP TABLE dbo.T_CURRENCY;

CREATE TABLE dbo.T_CURRENCY
(
  ID_CURRENCY   INT         NOT NULL IDENTITY(1, 1)
    CONSTRAINT PK_CURRENCY PRIMARY KEY,
  NAME VARCHAR(30)        NOT NULL,
  VALUTE_ID    VARCHAR(10) NOT NULL
);
GO

INSERT INTO [dbo].[T_CURRENCY] VALUES ('Швейцарский франк', 'R01775');
INSERT INTO [dbo].[T_CURRENCY] VALUES ('Японская йена', 'R01820');
GO

IF OBJECT_ID('dbo.T_RATE_OF_EXCHANGE', 'U') IS NOT NULL DROP TABLE dbo.T_RATE_OF_EXCHANGE;

CREATE TABLE dbo.T_RATE_OF_EXCHANGE
(
  ID_RATE   INT         NOT NULL IDENTITY(1, 1)
    CONSTRAINT PK_RATE_OF_EXCHANGE PRIMARY KEY,
  ID_CURENCY INT NOT NULL,
  VALUE numeric(19,4) NOT NULL,
  DateVal date NOT NULL
);
GO